### ISSUE TITLE
HA apim-analytics with two replicas instead of two dockers images apim-analytics-1 and apim-analytics-2

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#10]
Hi,

When run with two or more replicas, the apim-analytics can be resilient to failures, providing a highly-available service.

Why there is two dockers images apim-analytics-1 (https://github.com/wso2/kubernetes-apim/tree/2.1.0/pattern-1/dockerfiles/apim-analytics-1) and apim-analytics-2 (https://github.com/wso2/kubernetes-apim/tree/2.1.0/pattern-1/dockerfiles/apim-analytics-2) ?  While it is enough, from my point of view, a single image with 2 as a replica in the wso2apim-analytics-deployment.yaml file.

Thanks,
Youcef HILEM

**Comment by pubudu538** [comment]
This is due to a limitation in WSO2 DAS. One of the limitation is thrift. Thrift maintains a session and we cannot load balance due to this. To overcome several issues and to provide HA, we have used two images.

**Comment by yhilem** [comment]
Thank you.
