### ISSUE TITLE
Add Pattern 3 Fully distributed setup

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#157]
Hi,

Kubernetes resources for patterns 3 and 4 for the latest versions of WSO2 API Manager are expected to be part of the next immediate release.

[1] http://wso2-oxygen-tank.10903.n7.nabble.com/Announce-WSO2-Product-Installation-Resources-Released-tp158641p158650.html

Thanks
Youcef HILEM

**Comment by chirangaalwis** [comment]
Closing this issue as Kubernetes resources for WSO2 API Management v2.6.x deployment pattern 3 have been created in https://github.com/wso2/kubernetes-apim/pull/192.

Please see the corresponding issue created for Kubernetes resources for WSO2 API Management v2.6.x deployment pattern 4 (see https://github.com/wso2/kubernetes-apim/issues/193).
