### ISSUE TITLE
Helm APIM 2.6.0  helm chart has 2.5.0 paths.

### ISSUE THREAD

**Issue by gnudeep** [wso2/kubernetes-apim#169]
**Description:**

Helm apim 2.6.0  helm chart has 2.5.0 paths.
        volumeMounts:
        - name: apim-storage-volume
          mountPath: /home/wso2carbon/wso2am-2.5.0/repository/deployment/server

https://github.com/wso2/kubernetes-apim/blob/master/helm/pattern-1/apim-with-analytics/templates/wso2apim-deployment.yaml#L89

**Comment by ThilinaManamgoda** [comment]
We have fixed this in the 2.6.x branch. We will merge this into the master branch.
https://github.com/wso2/kubernetes-apim/pull/167
