### ISSUE TITLE
ERROR - EntitlementServiceComponent Failed to initialize Entitlement Service : Error in initializing thrift transport : org.apache.thrift.transport.TTransportException: Could not bind to port 10500

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#18]
Hi,

The exception "org.apache.thrift.transport.TTransportException: Could not bind to port 10500" is thrown when HostName and MgtHostName are not set to lacalhost in carbon.xml.

Exemple :

      
      <HostName>localhost</HostName>

        
	<MgtHostName>localhost</MgtHostName>
	

Thanks
Youcef HILEM

**Comment by pubudu538** [comment]
Based on the information which you have shared with us, it looks like that wso2apim-all.wso2.svc hostname does not resolve. Yes, it will work when you change that to localhost. 

You need to use the service name in HostName and MgtHostName. If your service name is apim-publisher, it will be resolved in the default namespace. But if you are using a different namespace, make sure you use the namespace included service name as below.

apim-publisher.<namespace>.svc

You can find more information in https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/networking.html

**Comment by yhilem** [comment]
Thank you,

In my configuration, the service **wso2apim-all** is resolved to :

Type: ClusterIP
IP: 172.30.142.170
Hostname: **wso2apim-all.wso2.svc** 
Session affinity: ClientIP

I am currently preparing to implement the pattern-2 that is our target on RedHat OpenShift 3.4.

The value of hostname in pattern-2/dockerfiles/apim-gw-manager-worker/carbon/repository/confcarbon.xml is **wso2apim-gw.default.svc**, which corresponds to:
- project name: default
- service name: wso2apim-gw

I will update according to the results that will get.

Thanks,
Youcef HILEM

**Comment by yhilem** [comment]
The exception is no longer thrown.
