### ISSUE TITLE
imagePullCredential reference not needed when using public docker images

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-apim#190]
**Description:**
The secret `wso2creds` is not created if username and password aren't given as values for the Helm charts. However the deployment manifest template contains reference (imagePullCredentials) to the above mentioned secret.

**Comment by Aaquiff** [comment]
#191

**Comment by Aaquiff** [comment]
Fixed in PR #191

**Comment by chirangaalwis** [comment]
Closing the issue as this is fixed in https://github.com/wso2/kubernetes-apim/pull/191.
