### ISSUE TITLE
Update images in all the patterns

### ISSUE THREAD

**Issue by pubudu538** [wso2/kubernetes-apim#211]
**Description:**

In these patterns, most of the images (diagrams) are not upto data. Need to update the images. Some contains manager/worker concepts which we had earlier and not applicable at the moment.

**Comment by chirangaalwis** [comment]
Fixed in commit https://github.com/wso2/kubernetes-apim/pull/235/commits/7c42885ba60e2fb75d135e4effec6a9186ca945b.
