### ISSUE TITLE
[pattern-1] No need to share User database

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-apim#217]
**Description:**

Currently, WSO2AM_COMMON_DB is shared between the APIM and analytics nodes. Although it doesn't cause any issue, it gives the idea that this database should be shared between the APIM and Analytics although it is not required. 

**Affected Product Version:**
Kubernetes and Helm resources for WSO2 API Manager version 2.6.0

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-apim/pull/223.
