### ISSUE TITLE
In a distributed API Manager setup, give the full URL of the authentication server in the <APIM_HOME>/repository/conf/identity/application-authentication.xml

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#23]
Hi,

It is stated in the documentation (https://docs.wso2.com/display/AM210/Authorization+Code+Grant) that
"In a distributed API Manager setup .... be sure to give the full URL of the authentication server in the <APIM_HOME>/repository/conf/identity/application-authentication.xml file. "

For my case (https://github.com/wso2/kubernetes-apim/tree/2.1.0/pattern-2), this configuration is not modified. Thus it's the default configuration that has a relative path, which works in a standalone API Manager that is applied.

In our case (with wso2apim-gw-route) , we have the following urls for:
- Authorize Endpoint : "https://wso2apim-gw/authorize"
- Token endpoint ? "https://wso2apim-gw/token"
- Userinfo endpoint ? "https://wso2apim-gw/userinfo"
- Revoke token endpoint ? "https://wso2apim-gw/revoke"

Thanks,
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

You need to use wso2apim-gw endpoint for all the endpoints. In pattern-2 this request is forwarded to key manager. But we only expose gateway endpoints. 

You can update application-authentication.xml file to specify the relevant url.

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Thank you Pubudu.
