### ISSUE TITLE
Use Built-in Release object (.Release.Namespace) for namespace

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-apim#243]
**Description:**
Currently the helm chart requires the namespace as a variable in addition to the helm namespace option and these needs to be the same. We could instead use the Built-in Release object to obtain the namespace (.Release.Namespace) that helm is deploying into.

**Comment by Aaquiff** [comment]
#241 Created to fix this

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-apim/pull/241.
