### ISSUE TITLE
Changing the admin password from the console also forces us to change it in the config. Thus, rebuild the dockers images and do another deployment.

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#25]
Hi,

Affter we have changed the admin password with console, we were forced to rebuild the dockers images by also changing the password in the config (because we are no longer able to login).
And of course, do another deployment.
Is this a bug?

Thanks
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

Yes, you have to update the passwords in the configuration files as well [1]. This is not a bug. For service calls, you need to provide username/passwords. Once you change the password of a server, you have to change on other servers where it has used.

[1] - https://docs.wso2.com/display/AM210/Maintaining+Logins+and+Passwords

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Thank you Pubudu.
