### ISSUE TITLE
Create Helm resources for WSO2 API Manager version 3.0.0 deployment pattern 1

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-apim#257]
**Description:**
Create Kubernetes resources for WSO2 API Manager version 3.0.0 deployment pattern 1 [1].

[1]: [Deployment pattern 1](https://docs.wso2.com/display/AM300/Deployment+Patterns#DeploymentPatterns-Pattern1)

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-apim/pull/264.
