### ISSUE TITLE
Create resources for WSO2 API Management version 3.0.0 MySQL Helm Chart

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-apim#260]
**Description:**
It is required to create Helm resources required to create a chart for WSO2 API Management version 3.0.0 database deployment in MySQL RDBMS. This chart is expected to be used for the evaluation of the WSO2 API Management deployment pattern Helm charts.

**Comment by Aaquiff** [comment]
Change done in #261

**Comment by chirangaalwis** [comment]
Closing the issue as it is fixed in the referenced PR.
