### ISSUE TITLE
Remove temporary fixes done for Helm APIM 3.0.0 pattern-1

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-apim#287]
**Description:**
Following temporary fixes were done for the release 3.0.0.1 of APIM pattern-1 Helm resources. These need to be removed as the fixes for these would be released in the GA docker images.
- Override fixed artifact for analytics dashboard. It contains the fix for the issue where it is not possible to disable hostname verification.
- Override jaggery apps to fix incorrect redirect URLs during OAuth authentication.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-apim/pull/288.
