### ISSUE TITLE
Helm chart for pattern 2 does not share RegDB with IS-KM

### ISSUE THREAD

**Issue by rksk** [wso2/kubernetes-apim#311]
Helm chart for pattern 2 does not share RegDB with IS-KM. Due to this issue, some flows like `creating tenants via IS-KM and accessing them via APIM` breaks. 

We have to add the registry.xml with reg mounts and data source into master-datasources. Also, relevant templates into `advanced/helm/am-pattern-2/templates/am-is-as-km/wso2am-pattern-2-is-as-km-conf-datasources.yaml`

**Comment by chirangaalwis** [comment]
@rksk the WSO2 API Management deployment pattern Helm Charts do not support multi tenancy by default. In other words, the evaluatory API Management Helm Charts are built for single tenant setups.

We expect the users to customize the default Helm Charts with the necessary configurations and artifact changes (e.g. persisting and sharing the `<APIM_HOME>/repository/tenants` directory) when necessary.

Else, we can provide an option to switch between a single tenant and multi tenanted environment via the `<HELM_HOME>/values.yaml` file.

@pubudu538 which one would be the recommended approach from the product team perspective?

**Comment by pubudu538** [comment]
@chirangaalwis Multi-tenancy should be there by default in Helm as well. So let's fix this. We should not bring any config in Helm.

**Comment by rksk** [comment]
It seems we have removed persistent volumes for IS-KM https://github.com/wso2/kubernetes-apim/pull/281/commits/abe305b7512be0d1697b8b5f37ec28f8bafc6def

But they have to be there if we are going to support tenancy,

**Comment by rksk** [comment]
Moved to https://github.com/wso2/kubernetes-apim/issues/319 since the subject is misguiding.
