### ISSUE TITLE
Create wso2-apim support to run on OpenShift v3.11

### ISSUE THREAD

**Issue by fsbano** [wso2/kubernetes-apim#334]
**Description:**
Create wso2-apim support to run on openshift

**Affected Product Version:**
wso2-apim-3.0.0 

**OS, DB, other environment details and versions:**    
OpenShift v3.11

**Comment by Chathuru** [comment]
We have developed OpenShift resources for WSO2 products. For wso2-apim version 3.1.0 you can find the OpenShift resource in https://github.com/Chathuru/wso2-openshift-apim here. We will merge these resources into WSO2 repose soon.

**Comment by chirangaalwis** [comment]
@fsbano we have performed the initial release of Openshift resources for WSO2 API Management version `3.1.0` deployments (please refer release [tag](https://github.com/wso2/openshift-apim/releases/tag/v3.1.0.1)).

Hence, closing this issue.
