### ISSUE TITLE
[v3.1.x] No image found at wso2/apim-pattern-1

### ISSUE THREAD

**Issue by hackdan** [wso2/kubernetes-apim#356]
**Description:**
I try install pattern-1 as describe in the read me file but i have this error:
[debug] Original chart version: "3.1.0-1"
Error: chart "apim-pattern-1" matching version "3.1.0-1" not found in wso2 index. (try 'helm repo update'). no chart name found 

**Steps to reproduce:**
helm install --name wso2v1 wso2/apim-pattern-1 --version 3.1.0-1 --namespace default --debug

**Comment by Aaquiff** [comment]
@hackdan Sorry for the confusion, there is a mistake in the instructions.
Please try `wso2/am-pattern-1` instead of `wso2/apim-pattern-1`

**Comment by hackdan** [comment]
@Aaquiff Great thank you for the help, and super fast answare. The chart works but with new issue, i don't know if we close this thread and open other issue, (please tell me), the issue: 
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

**Comment by Aaquiff** [comment]
@hackdan may I know the Helm and Kubernetes version you are using?

**Comment by 13940344135** [comment]
I encountered the same issues:
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

I am using：
minikube:1.9.2
kubernetes:1.8.0
helm:3.1.2

**Comment by chirangaalwis** [comment]
Closing this issue based on https://github.com/wso2/kubernetes-apim/issues/369#issuecomment-620407669 and as the original issue has been addressed.

Please feel free to reopen this issue for further clarification, if needed.
