### ISSUE TITLE
simple/deployment-scripts/wso2am-ga.sh not working in a Kubernetes in Docker For Desktop in MAC

### ISSUE THREAD

**Issue by fjunior87** [wso2/kubernetes-apim#361]
**Description:**
Tried to use the wso2am-ga.sh for the simple deployment in a local Kubernetes cluster that comes with Docker For Desktop in MacOS and I got the following error:
```
± |master U:1 ✗| → ./wso2am-ga.sh --deploy
Checking for an enabled cluster... Your patience is appreciated... Done


*         *    * * *      * * *      * * *              * * *     * * *    * * * * *   *         *
*         *   *     *   *       *   *     *            *     *    *     *      *       * *     * *
*    *    *   *         *       *         *           *       *   *     *      *       *  *   *  *
*   * *   *    * * *    *       *       *     * * *   * * * * *   * * *        *       *   * *   *
*  *   *  *         *   *       *     *               *       *   *            *       *    *    *
* *     * *   *     *   *       *   *                 *       *   *            *       *         *
*         *    * * *      * * *     * * * *           *       *   *        * * * * *   *         *


💣  Error getting IP: Host is not running

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

It looks like the script looks for an external IP and in my case where I am using Docker for Desktop it does not have that.

**OS, DB, other environment details and versions:**    
OS: Mac OS
Docker For Desktop: 2.1.0.3
Kubernetes: v1.14.6

**Comment by chirangaalwis** [comment]
@fjunior87 Just for clarity, what is the WSO2 API Management version for which you are using this script?

**Comment by fjunior87** [comment]
Hi @chirangaalwis I am using the latest one from master branch, 3.1.0.

**Comment by NishikaDeSilva** [comment]
@fjunior87 Since this deployment is based node-ip service type we are searching for an external cluster IP. However, since the cluster is in a local environment the script is unable to get one. 
We have handled this case for minikube. I will be opening an issue for this to provide a solution asap.

In the meantime, since you already have minikube may I suggest you deploying this on minikube? 

Please note that minikube's existing configurations do not meet with our deployment requirements. So, please change the configurations before running the wso2am-ga.sh. 

```
$ minikube config set memory 11264
$ minikube config set cpus 7 

$ minikube delete
$ minikube start
```

**Comment by fjunior87** [comment]
Thanks @NishikaDeSilva

**Comment by chirangaalwis** [comment]
@NishikaDeSilva shall we create a new issue for the fix you are going to introduce?

@fjunior87 did you manage to deploy this setup in Minikube? If yes, since @NishikaDeSilva is going to cover this via a separate issue, shall we please close this issue?

**Comment by fjunior87** [comment]
Hi @chirangaalwis , I did not try it in minikube, but I believe we can close the issue.
Thanks

**Comment by NishikaDeSilva** [comment]
I've opened a new issue #363, thus I will close this issue.

@fjunior87 please feel free to ask any concerns in the newly opened issue ( #363 )

**Comment by chirangaalwis** [comment]
Closing this issue.
