### ISSUE TITLE
[v3.1.x] Support for Custom Kubernetes Storage Class

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-apim#362]
**Description:**
Currently, the API Management Helm charts use [`stable/nfs-server-provisioner`](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) for deploying an in-cluster NFS server and for an external NFS server we have used Kubernetes based Persistent Volumes.

Instead, I would like to suggest allowing a user to define any custom Kubernetes Storage Class in the `values.yaml`. In documentation, we can suggest how a user can plug an external NFS server using the [`stable/nfs-client-provisioner`](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner).

**Comment by chirangaalwis** [comment]
[This](https://cloud.google.com/community/tutorials/gke-filestore-dynamic-provisioning) documentation suggests how we can use Google Cloud Filestore service with `stable/nfs-client-provisioner`.

**Comment by chirangaalwis** [comment]
@ThilinaManamgoda @rasanjaya85 @DilanUA @Chathuru your suggestions and concerns are highly appreciated.

**Comment by rasanjaya85** [comment]
What did you mean by any custom Kubernetes storage?  What type of storage class are we planning to support i.e: cept, glusterfs ?

**Comment by chirangaalwis** [comment]
@rasanjaya85 yes.

Also, we should ideally be able to plug `nfs-client-provisioner` as a Storage Class. This type of Storage Class takes in an external NFS server IP and uses that server for creating storage volumes from the allocated storage. IMO, we can use this Storage Class rather than defining individual Persistent Volumes.

**Comment by ThilinaManamgoda** [comment]
@chirangaalwis +1 for the suggestion. Are we removing the current implementation?

**Comment by chirangaalwis** [comment]
@ThilinaManamgoda IMO, we have to evaluate the pros and cons of `nfs-client-provisioner` further.

This ideally should be the way in which we should allow users to configure an external NFS server. But the drawback is that in such a case, this becomes a prerequisite.

Further, we should also consider the permission related issues. When evaluating it with the use of Google Cloud Filestore, the volumes are mounted into the containers with `root` user ownership. But, it sets read-write-execute permissions for all users, by default. Thus, it worked fine.

**Comment by ThilinaManamgoda** [comment]
@chirangaalwis The Only concern I have is this becoming a prerequisite. We initially took this approach to make a pleasant first-time experience without bringing the NFS server complication into the picture. How are we going to address this?

**Comment by chirangaalwis** [comment]
> @chirangaalwis The Only concern I have is this becoming a prerequisite. We initially took this approach to make a pleasant first-time experience without bringing the NFS server complication into the picture. How are we going to address this?

I think since we use the `nfs-server-provisioner` as the default, this will serve the purpose you have highlighted. After all, if a user intends to use an external NFS server, installing the server, preparing the directories and setting the configurations are manual tasks which collectively become a prerequisite.

Using the `nfs-client-provisioner` only requires you to provide the provide the base exported directory path and the server IP. It creates the necessary directories based on the request storage size and serves the purpose.

So, I think in when using an external NFS server instance, a user has to perform a few prerequisite tasks in preparing the NFS server. Using the `nfs-client-provisioner` makes those tasks easier.

My concern is as to how this would work in other environments (e.g. cloud environments such as, AWS and in bare metal clusters). I have so far tested this in GKE, only.

**Comment by ThilinaManamgoda** [comment]
+1 for making `nfs-server-provisioner` as the default. For other environments, we can ask for an NFS server endpoint, right?

**Comment by chirangaalwis** [comment]
> +1 for making `nfs-server-provisioner` as the default.

@ThilinaManamgoda we already have `nfs-server-provisioner` as the default.

> For other environments, we can ask for an NFS server endpoint, right?

I think we can avoid this if we recommend users to utilize the `nfs-client-provisioner`. They have to install the `nfs-client-provisioner` in the cluster (one time installation). During this installation, they need to provide the NFS server IP. Then, the generated Storage Class should be referred in WSO2 Helm Chart `values.yaml`. This is the reason why I suggested moving to a model of using strictly Kubernetes Storage Classes and avoiding the need to define Persistent Volume resources.

**Comment by rasanjaya85** [comment]
+1 for making the nfs-client-provisioner as default. Then is required to test this with all the major cloud providers since setting up the NFS server is easier than compare to configure the GlsusterFS, Ceph, and Swift.  Further it's more difficult to set the object storage solution compare with block storage solutions.

**Comment by chirangaalwis** [comment]
> +1 for making the nfs-client-provisioner as default.

@rasanjaya85 IMO, `nfs-server-provisioner` should remain the default. This is to avoid the user the need to provide an external NFS server as a prerequisite. But yes, when using an external NFS server, we should recommend a user to utilize the `nfs-client-provisioner`.

> Then is required to test this with all the major cloud providers since setting up the NFS server is easier than compare to configure the GlsusterFS, Ceph, and Swift. Further it's more difficult to set the object storage solution compare with block storage solutions.

+1 for testing.

**Comment by chirangaalwis** [comment]
Improved to use Kubernetes Storage Class resources in all API Management Helm Charts in https://github.com/wso2/kubernetes-apim/pull/365.
