### ISSUE TITLE
[v3.1.x] Simplified setup doesn't support local environments

### ISSUE THREAD

**Issue by NishikaDeSilva** [wso2/kubernetes-apim#363]
**Description:**
kubernetes-apim simplified setup does not support any local environment (i.e. kubernetes cluster in Docker for Desktop) other than Minikube. 

**Affected Product Version:**
Kubernetes resources for WSO2 API Management version `3.1.0.1`

**Steps to reproduce:**
Running the kubernetes-apim simplified setup in kubernetes cluster in docker for desktop. 

**Related Issues:**
#361

**Comment by chirangaalwis** [comment]
This has been fixed in Kubernetes resources for API Management version `3.2.0`. Thus, moving to milestone `3.2.0.2`
