### ISSUE TITLE
[v3.1.x] Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by 13940344135** [wso2/kubernetes-apim#369]
**Description:**
An error occurred while deploying using the command：
helm install ap2 wso2/am-pattern-2 --version 3.1.0-1 --namespace default
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

**Affected Product Version:**
v3.1.0-1

**OS, DB, other environment details and versions:**    
windows10，minikube1.9.2，kubernetes1.18.0，kubectl1.18.2，helm3.1.2

**Steps to reproduce:**
1. helm repo add wso2 https://helm.wso2.com
2. helm repo update
3. helm install amp2 wso2/am-pattern-2 --version 3.1.0-1 --namespace default
OR
1. git clone https://github.com/wso2/kubernetes-apim.git
2. helm dependency update C:\Users\Administrator\Desktop\WSO2\kubernetes-apim\advanced/am-pattern-2
3. helm install amp2 C:\Users\Administrator\Desktop\WSO2\kubernetes-apim\advanced/am-pattern-2 --namespace default

**Comment by 13940344135** [comment]
How can I avoid it?

**Comment by Chathuru** [comment]
Seems like helm 3 still doesn't support Kubernetes 1.18. Please refer

[1] - https://github.com/helm/helm/issues/6981#issuecomment-555098429
[2] -https://helm.sh/docs/topics/kubernetes_distros/

**Comment by 13940344135** [comment]
https://github.com/wso2/kubernetes-apim/issues/369#issuecomment-620407669
Thank you very much for your answer
