### ISSUE TITLE
Improve CPU and memory allocation for APIM products

### ISSUE THREAD

**Issue by manjulaRathnayaka** [wso2/kubernetes-apim#375]
**Description:**
Increasing the k8s deployment resource limits has no impact on allocated resources to the JVM. 

Solution: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits

**Suggested Labels:**
Production Hardening Guidelines

**Comment by chirangaalwis** [comment]
We will be adding this support for releases from API Manager version `3.2.0`. Thus, changing the milestone.

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-apim/pull/451.
