### ISSUE TITLE
Add support for Key store and Trust store mounting

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-apim#378]
**Description:**
In the current APIM Helm charts, we haven't provided a way to customize the Keystore and Trust store for the deployment. Since this is a valid requirement, this needs to be addressed. It is required to explore the ability to mount binary files using ConfigMaps for this scenario and add a comprehensive document on this feature.

**Comment by chirangaalwis** [comment]
@ThilinaManamgoda we already have created an issue mapping to this. Please refer https://github.com/wso2/kubernetes-apim/issues/367.

I suppose we can track the additionally suggested documentation details using this issue.

**Comment by chirangaalwis** [comment]
We will be adding this support for releases from API Manager version `3.2.0`. Thus, changing the milestone.

**Comment by chirangaalwis** [comment]
Fixed in documentation.
