### ISSUE TITLE
the POD status is pending and init: 0/2

### ISSUE THREAD

**Issue by 13940344135** [wso2/kubernetes-apim#380]
**Description:**
After WSO2 deployment is successful, the POD status is pending and init: 0/2.

I set up am-pattern-2 of WSO2 using bare metal cluster.
The cluster hardware information is as follows:
node1: 5-core 10-thread CPU, 22GB memory.
node2: 2 core 4 thread CPU, 8GB memory.
node3: 2 core 4 thread CPU, 8GB memory.
node4: 2 core 4 thread CPU, 8GB memory.

The POD status of the deployment is as follows:
NAMESPACE       NAME                                                              READY   STATUS     RESTARTS   AGE
ingress-nginx   nginx-ingress-controller-585f5478d8-7c8f9                         1/1     Running    0          15h
kube-system     calico-kube-controllers-789f6df884-sk89m                          1/1     Running    0          15h
kube-system     calico-node-5fdgj                                                 1/1     Running    1          17h
kube-system     calico-node-5fdmx                                                 1/1     Running    0          18h
kube-system     calico-node-ldcsg                                                 1/1     Running    0          18h
kube-system     calico-node-vsdn9                                                 1/1     Running    1          17h
kube-system     coredns-7ff77c879f-f5lbx                                          1/1     Running    0          18h
kube-system     coredns-7ff77c879f-kwn5w                                          1/1     Running    0          18h
kube-system     etcd-localhost.localdomain1                                       1/1     Running    0          18h
kube-system     kube-apiserver-localhost.localdomain1                             1/1     Running    0          18h
kube-system     kube-controller-manager-localhost.localdomain1                    1/1     Running    0          18h
kube-system     kube-proxy-7b7ms                                                  1/1     Running    1          17h
kube-system     kube-proxy-hr96l                                                  1/1     Running    0          18h
kube-system     kube-proxy-qtrn9                                                  1/1     Running    1          17h
kube-system     kube-proxy-xthf5                                                  1/1     Running    0          18h
kube-system     kube-scheduler-localhost.localdomain1                             1/1     Running    1          18h
wso2            ap2-nfs-server-provisioner-0                                      1/1     Running    0          17m
wso2            wso2am-mysql-db-service-689d95777b-z7rp6                          0/1     Pending    0          17m
wso2            wso2am-pattern-2-am-analytics-dashboard-deployment-7d689689hcqr   0/1     Init:0/2   0          17m
wso2            wso2am-pattern-2-am-analytics-worker-2-deployment-5b697497tsjmb   0/1     Init:0/1   0          17m
wso2            wso2am-pattern-2-am-analytics-worker-deployment-5487c68c5dlr5sn   0/1     Init:0/1   0          17m
wso2            wso2am-pattern-2-am-km-deployment-5d9df8d478-27msh                0/1     Init:0/3   0          17m
wso2            wso2am-pattern-2-am-km-deployment-5d9df8d478-8lw6n                0/1     Init:0/3   0          17m
wso2            wso2am-pattern-2-gateway-deployment-89d4d8b89-kzs6h               0/1     Init:0/2   0          17m
wso2            wso2am-pattern-2-gateway-deployment-89d4d8b89-zzb97               0/1     Pending    0          17m
wso2            wso2am-pattern-2-pub-store-tm-1-deployment-0                      0/1     Init:0/2   0          17m
wso2            wso2am-pattern-2-pub-store-tm-2-deployment-0                      0/1     Pending    0          17m

Query the information of one of the pods as follows:
kubectl describe pods wso2am-pattern-2-pub-store-tm-2-deployment-0 -n wso2：
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "wso2am-pattern-2-pub-store-tm-2-deployment-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "wso2am-pattern-2-pub-store-tm-2-deployment-0": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 4 Insufficient cpu.

**Affected Product Version:**
version 3.1.0-2

**Steps to reproduce:**
helm install ap2 wso2/am-pattern-2 --version 3.1.0-2 --namespace wso2

**Related Issues:**
Is it because of insufficient resources that it cannot run? what should I do?

**Comment by chirangaalwis** [comment]
@13940344135 as per the `Events` this is due to a missing, underlying storage solution from which Persistent Volumes are to be created. Thus, you get failed unbound Persistent Volume Claims.

You need to configure a Kubernetes Storage Class which points to an appropriate source from which Kubernetes can dynamically generate Persistent Volumes (e.g. a VM with a NFS server installed).

**Comment by 13940344135** [comment]
@ @chirangaalwis 
Thank you for your quick answer,
I am trying to install NFS,
If you can provide more detailed installation commands, I will be very grateful.

**Comment by chirangaalwis** [comment]
@13940344135 you can use the [NFS Client Provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner) for this purpose.

- Prepare a VM with the NFS Server installed. For example this is [how](https://help.ubuntu.com/community/SettingUpNFSHowTo) we can install a NFS server in Ubuntu. Please note that the VM should be accessible from the Kubernetes cluster worker nodes.

- [Install the NFS Client Provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner#installing-the-chart). You may provide the IP of the VM in which the NFS Server is installed as the source for this client provisioner.

- Set the [name](https://github.com/wso2/kubernetes-apim/blob/v3.1.0.2/advanced/am-pattern-2/values.yaml#L43) of the Storage Class to point to the NFS Client Provisioner.

**Comment by 13940344135** [comment]
@chirangaalwis 
thank you very much
thank you very much
thank you very much

**Comment by 13940344135** [comment]
@chirangaalwis I found a POD named ap2-nfs-server-provisioner-0 in the am-pattern-2 I installed,
What is this nfs-server? Can it be used?
