### ISSUE TITLE
am-pattern-1~am-pattern-3 difference 

### ISSUE THREAD

**Issue by 13940344135** [wso2/kubernetes-apim#385]
What is the difference between am-pattern-1, am-pattern-2, and am-pattern-3? How should I choose?

**Comment by chirangaalwis** [comment]
> What is the difference between am-pattern-1, am-pattern-2, and am-pattern-3?

@13940344135 these stand for different, standard [deployment patterns](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-patterns/) of WSO2 API Manager.

We have created a Helm chart for each product deployment pattern.

> How should I choose?

Please refer the official [documentation](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-patterns/) for details on how to choose the most appropriate pattern for your requirements.

**Comment by 13940344135** [comment]
Thank you for your answer
