### ISSUE TITLE
Need to correct the advertisedHost value in the Analytics Active/Passive configuration.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/kubernetes-apim#387]
**Description:**
When configuring the Analytics Active/Passive setup, it needs to set the own server IP address for the host and advertisedHost properties. But in this configuration[1], it has configured the other node IP address for the advertisedHost property. It should be changed to the hostname of its own server.

[1] - https://github.com/wso2/kubernetes-apim/blob/v3.1.0.2/advanced/am-pattern-1/templates/am-analytics/worker/wso2am-pattern-1-am-analytics-worker-deployment.yaml#L56

**Affected Product Version:**
APIM-Analytics-3.1.0

**Comment by chirangaalwis** [comment]
Adding a related issue - https://github.com/wso2/kubernetes-apim/issues/358

**Comment by chirangaalwis** [comment]
Fixed in referenced PRs.
