### ISSUE TITLE
Error in "simplified script" bash : wrong test

### ISSUE THREAD

**Issue by Marsu31** [wso2/kubernetes-apim#395]
Hi,

In the two scripts wso2am-ga.sh and wso2-latest.sh this test is wrong:
`if [[ $(kubectl config current-context)="minikube" ]]`
it must be:
`if [[ $(kubectl config current-context) = "minikube" ]]`
with spaces around the = symbol

Regards

**Comment by chirangaalwis** [comment]
Fixed in the referenced PR.
