### ISSUE TITLE
[3.2.0] Test Ingress with Custom TLS Certificate

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-apim#402]
**Description:**
It is required to test the Ingress with custom TLS Certificate.

Since, WSO2 recommends the use of Kubernetes [NGINX Ingress Controller](https://kubernetes.github.io/ingress-nginx/) for exposing internal services to outside of the Kubernetes cluster.

Resources to refer to:
- [Official Guide](https://kubernetes.github.io/ingress-nginx/user-guide/tls/)
- [Generate TLS Secret for kubernetes](https://software.danielwatrous.com/generate-tls-secret-for-kubernetes/)

**Comment by chirangaalwis** [comment]
There are numerous solutions when configuring custom TLS certificates in Ingress Controllers. Some of these approaches differ with the Ingress Controller solution used (e.g. [AWS ALB Ingress Controller](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#certificate-arn)).

Thus, let us highlight the most common approach in achieving this, which can be used with the default Community NGINX Ingress Controller solution.

- Create the private key and the certificate as desired

- Create and deploy a Kubernetes Secret of type `kubernetes.io/tls` using the private key and the certificate

For the above two steps, we recommend you to refer to [this](https://software.danielwatrous.com/generate-tls-secret-for-kubernetes/) write up.

- Refer to the created Kubernetes Secret in the relevant Ingress resource as follows:

```
kind: Ingress
...
spec:
  tls:
    - hosts:
        - <hostname-for-which-certificate-should-be-received>
      secretName: <kubernetes-secret-name>
```

**Comment by chirangaalwis** [comment]
Closing this issue as we have added the necessary instructions in https://github.com/wso2/kubernetes-apim/issues/402#issuecomment-682011089 and have documented pointers to the best practices in the [official WSO2 container guide](https://github.com/wso2/container-guide), when configuring SSL.

**Comment by karezza** [comment]
I wish to note that the information you have given on how to setup tls via an ingress is very common and very easy to find.  Probably, what people are actually asking, and what I am currently looking for, is how to setup this tls configuration via the helm style install being provided in this project.  Is this as simple as setting the tls certs in the values file & running helm again?  Are the cert values in the chart?   If not, perhaps they could be added and if set then the tls section could be used ... and if not it could be skipped.  These directions you have provided are a good starting point for someone who hasn't setup a tls via ingress before, but there is still an opportunity to improve the documentation from a helm-specific perspective.
