### ISSUE TITLE
Test API Management Deployments with CephFS Storage Solution

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-apim#410]
**Description:**
It was identified that CephFS could be used as a storage solution in WSO2 product deployments in Kubernetes since, it supports `ReadWriteMany` [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes).

This has to be tested.

**Comment by chirangaalwis** [comment]
WSO2 recommends the use of [Rook Operator](https://rook.io/docs/rook/v1.3/ceph-quickstart.html) to create a CephFS cluster in Kubernetes. Rook stands as the leader among Cloud Native storage [solutions](https://landscape.cncf.io/category=cloud-native-storage&format=card-mode&grouping=category&selected=rook).

The steps that need to be followed for the installation are given below:

- Deploy the Rook Operator

Please follow section Deploy the [Rook Operator](https://rook.io/docs/rook/v1.3/ceph-quickstart.html) in this document.

- Create a Rook Ceph Cluster using a PVC

Please see [this](https://github.com/rook/rook/blob/release-1.3/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml) documentation for an example.

You may use the Kubernetes StorageClass of your desire to create the underlying Persistent Volumes, by setting the StorageClass name at [[1](https://github.com/rook/rook/blob/release-1.3/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L30)] and [[2](https://github.com/rook/rook/blob/release-1.3/cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml#L114)].

- [Optional] Install the [Rook Tool Box](https://rook.io/docs/rook/v1.3/ceph-toolbox.html) to observe the health status of the CephFS cluster created

- Create a filesystem to be shared across multiple Pods using the instructions [here](https://rook.io/docs/rook/v1.3/ceph-filesystem.html).

**Comment by ThilinaManamgoda** [comment]
I think we can list down all the pre-requisites for the Rook + Ceph with the following docs,

- https://rook.io/docs/rook/v1.3/k8s-pre-reqs.html
- https://rook.io/docs/rook/v1.3/ceph-prerequisites.html

**Comment by chirangaalwis** [comment]
> I think we can list down all the pre-requisites for the Rook + Ceph with the following docs,
> 
> * https://rook.io/docs/rook/v1.3/k8s-pre-reqs.html
> * https://rook.io/docs/rook/v1.3/ceph-prerequisites.html

@ThilinaManamgoda added to https://github.com/wso2/kubernetes-apim/issues/410#issuecomment-654070688.

Will close this issue once we test all, existing deployment patterns with the suggested storage solution.

**Comment by chirangaalwis** [comment]
Tested Helm resources for API Manager deployment patterns 1, 2 and 3 (release tag https://github.com/wso2/kubernetes-apim/releases/tag/v3.1.0.3) with CephFS. Managed to successfully deploy and test the setups.

**Comment by ThilinaManamgoda** [comment]
Closing this issue since the storage solution **CephFS** has been tested with API Manager deployment patterns 1, 2 and 3 (release tag https://github.com/wso2/kubernetes-apim/releases/tag/v3.1.0.3).
