### ISSUE TITLE
Unnecessary resource limits in Kubernetes simplified setup

### ISSUE THREAD

**Issue by NishikaDeSilva** [wso2/kubernetes-apim#459]
**Description:**

Current k8s simplified setup requests 
      - 2 GB for APIM 
      - 4 GB for Analytics

Since the simplified setup is not recommended for production and solely for evaluation purposes, it does not require that many resources. Thus it is better to revise the resource limits for the setup

**Comment by chirangaalwis** [comment]
Fixed.
