### ISSUE TITLE
[3.1.0] Preparing for release v3.1.0.4

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/kubernetes-apim#471]
**Description:**
Preparing the repository for the release `v3.1.0.4`.

- [x] Upgrade APIM MySQL chart version
- [x] Upgrade APIM chart version
- [x] Update Docs
- [x] Update changelog

**Affected Product Version:**
APIM 3.1.0

**Comment by chirangaalwis** [comment]
Fixed.
