### ISSUE TITLE
helm install wso2 wso2/am-single-node  -> "Error: INSTALLATION FAILED: chart "am-single-node" matching "

### ISSUE THREAD

**Issue by doug62** [wso2/kubernetes-apim#589]
These commands:
helm repo add wso2 https://helm.wso2.com/
helm repo update
helm install wso2 wso2/am-single-node --namespace wso2 --create-namespace  --values=my-values.yml 
 
PRODUCES:
Error: INSTALLATION FAILED: chart "am-single-node" matching  not found in wso2 index. (try 'helm repo update'): no chart version found for am-single-node-
 
AND:
helm search repo wso2
 
PRODUCES:
wso2/kubernetes-pipeline        1.2.0           1.2.0           A Helm chart to deploy a CI/CD Pipeline in a Ku...   
wso2/mysql                      1.6.9           5.7.30          Fast, reliable, scalable, and easy to use open-...   
wso2/nfs-server-provisioner     1.1.0           2.3.0           nfs-server-provisioner is an out-of-tree dynami...   
wso2/spinnaker                  2.2.6           1.16.2          Open source, multi-cloud continuous delivery pl...   
 
Meaning - the am-single-node chart doesn't exist.

**Comment by tuananh** [comment]
I'm facing the same issue. Only the 4 charts above is available

**Comment by tuananh** [comment]
looks like the version is failing helm semver check `4.1.0-2` is not considered a valid semver it seems.

i tested by changing the local cached index to `4.1.0` and it shows up.

**Comment by doug62** [comment]
@PasanT9  - Thanks for including your 'helm search repo wso2 --devel' command, i was unaware of the --devel option and now I do see the charts.  Now when I install i get:
![image](https://github.com/wso2/kubernetes-apim/assets/5632034/8cca597d-776e-454d-93e4-2bb39bf2eb64)
I'm running K8-1.23.7 but have tried other versions.  I also tried different storage classes and had the same issue.

What is the recommended K8 version? (Thanks)

**Comment by PasanT9** [comment]
Hi @doug62,

I was able to successfully deploy the am-single-node cluster in Kubernetes v1.26.3. 

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```
In your case, note that the init condition for the db-service has not yet completed.

**Comment by PasanT9** [comment]
Closing the due to inactivity. Please reopen if needed.
