### ISSUE TITLE
Timeline for update to 2.2?

### ISSUE THREAD

**Issue by HolySamosa** [wso2/kubernetes-apim#80]
**Description:**
Given that API Manager 2.2 was just released, is there a timeline for supporting 2.2 with this project?

If this isn't imminent, aside from following the 2.1 -> 2.2 upgrade documentation, any recommendations on installing 2.2 using this project?  We were getting close to deploying 2.1, but are considering options for deploying 2.2 and avoiding the need to update.

Thanks!

**Suggested Labels:**
Question

**Comment by HolySamosa** [comment]
Just wanted to refresh this question.  Having gotten 2.1 up and running and configured for our organization, I've realized that WSO2 API Manager has lots of moving parts, is quite complex and can be a significant undertaking to configure for self-hosting.  (Unfortunately, cloud hosting isn't an option for this organization).  Before I take on trying to upgrade to 2.2 before our system goes into production, it would be great to know if the __kubernetes-apim__ project will be upgraded to 2.2.  In which case, we may wait for the official upgrade to gain the benefit of someone more experienced with the system.

Thanks so much for all of your work.

(@pubudu538 , @imesh-- I hope you don't mind that I call your attention to my question.  I just see that you are the most recent merge committers.  Thank you!)

**Comment by isurulucky** [comment]
Hi @HolySamosa, 
Sorry for the belated reply. At the moment we are internally updating this artifacts for the latest release of WSO2 API Manager, which is 2.5.0. This will be available by mid-July.

**Comment by HolySamosa** [comment]
@isurulucky Thanks a lot!  Looking forward to the update.
