### ISSUE TITLE
Add deploy-openshift.sh and undeploy-openshift.sh scripts for pattern-3

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#9]
Hi,

There is deploy-openshift.sh and undeploy-openshift.sh scripts for pattern-1 and pattern-2.

But not for pattern-3.

Can you please add deploy-openshift.sh and undeploy-openshift.sh scripts for pattern-3 ?

Thanks,
Youcef HILEM

**Comment by pubudu538** [comment]
We are currently working on those. These patterns will change slightly.

**Comment by yhilem** [comment]
Thank you.
